### PR TITLE
Fix bug that wasn't support local path as prefix

### LINKED ISSUE #1: possibility to prefix local path like '../../public/dist/'
in current version if i'll set something like
`        prefix: '../../public/dist/',
`
no prefixes will be added

### PR DESCRIPTION
**Pull request by wangpin34**
For fix: https://github.com/Justinidlerz/html-webpack-prefix-plugin/issues/1

### CODE REVIEW

**Comment by wangpin34** [comment]
@Justinidlerz Please help to review.

File: index.js [hunk 1]
```diff
@@ -66,8 +66,13 @@ HtmlWebpackPrefixPlugin.prototype.addPrefix = function ( html, options ){
         html = [html];
         links.forEach(function(link) {
             if (/^http[s]?:\/\/|^\/\//i.test(link.value)) return;
-            var value = url.resolve(options.prefix, link.value);
-
+            
+            var value;
+            if (options.prefix.indexOf('.') === 0) {
+                value = path.join(options.prefix, link.value).replace(/\\/ig, '\/')
```
Comment (wangpin34) [inline index.js:72]: Replace is for correcting path separator.
